package io.github.d0ublew.bapp.starter.dataclass

import burp.api.montoya.http.message.HttpRequestResponse

data class Checklist(
    val id: String,
    val title: String,
    val name: String
)

val CHECKLIST = mutableListOf<Checklist>(
    Checklist("WSTG-INFO-01", "Information Gathering", "Conduct Search Engine Discovery Reconnaissance for Information Leakage"),
    Checklist("WSTG-INFO-02", "Information Gathering", "Fingerprint Web Server"),
    Checklist("WSTG-INFO-03", "Information Gathering", "Review Webserver Metafiles for Information Leakage"),
    Checklist("WSTG-INFO-04", "Information Gathering", "Enumerate Applications on Webserver"),
    Checklist("WSTG-INFO-05", "Information Gathering", "Review Webpage Content for Information Leakage"),
    Checklist("WSTG-INFO-06", "Information Gathering", "Identify application entry points"),
    Checklist("WSTG-INFO-07", "Information Gathering", "Map execution paths through application"),
    Checklist("WSTG-INFO-08", "Information Gathering", "Fingerprint Web Application Framework"),
    Checklist("WSTG-INFO-09", "Information Gathering", "Fingerprint Web Application"),
    Checklist("WSTG-INFO-10", "Information Gathering", "Map Application Architecture"),
    Checklist("WSTG-CONF-01", "Configuration and Deploy Management Testing", "Test Network Infrastructure Configuration"),
    Checklist("WSTG-CONF-02", "Configuration and Deploy Management Testing", "Test Application Platform Configuration"),
    Checklist("WSTG-CONF-03", "Configuration and Deploy Management Testing", "Test File Extensions Handling for Sensitive Information"),
    Checklist("WSTG-CONF-04", "Configuration and Deploy Management Testing", "Review Old Backup and Unreferenced Files for Sensitive Information"),
    Checklist("WSTG-CONF-05", "Configuration and Deploy Management Testing", "Enumerate Infrastructure and Application Admin Interfaces"),
    Checklist("WSTG-CONF-06", "Configuration and Deploy Management Testing", "Test HTTP Methods"),
    Checklist("WSTG-CONF-07", "Configuration and Deploy Management Testing", "Test HTTP Strict Transport Security"),
    Checklist("WSTG-CONF-08", "Configuration and Deploy Management Testing", "Test RIA cross domain policy"),
    Checklist("WSTG-CONF-09", "Configuration and Deploy Management Testing", "Test File Permission"),
    Checklist("WSTG-CONF-10", "Configuration and Deploy Management Testing", "Test for Subdomain Takeover"),
    Checklist("WSTG-CONF-11", "Configuration and Deploy Management Testing", "Test Cloud Storage"),
    Checklist("WSTG-IDNT-01", "Identity Management Testing", "Test Role Definitions"),
    Checklist("WSTG-IDNT-02", "Identity Management Testing", "Test User Registration Process"),
    Checklist("WSTG-IDNT-03", "Identity Management Testing", "Test Account Provisioning Process"),
    Checklist("WSTG-IDNT-04", "Identity Management Testing", "Testing for Account Enumeration and Guessable User Account"),
    Checklist("WSTG-IDNT-05", "Identity Management Testing", "Testing for Weak or unenforced username policy"),
    Checklist("WSTG-ATHN-01", "Authentication Testing", "Testing for Credentials Transported over an Encrypted Channel"),
    Checklist("WSTG-ATHN-02", "Authentication Testing", "Testing for Default Credentials"),
    Checklist("WSTG-ATHN-03", "Authentication Testing", "Testing for Weak Lock Out Mechanism"),
    Checklist("WSTG-ATHN-04", "Authentication Testing", "Testing for Bypassing Authentication Schema"),
    Checklist("WSTG-ATHN-05", "Authentication Testing", "Testing for Vulnerable Remember Password"),
    Checklist("WSTG-ATHN-06", "Authentication Testing", "Testing for Browser Cache Weaknesses"),
    Checklist("WSTG-ATHN-07", "Authentication Testing", "Testing for Weak Password Policy"),
    Checklist("WSTG-ATHN-08", "Authentication Testing", "Testing for Weak Security Question Answer"),
    Checklist("WSTG-ATHN-09", "Authentication Testing", "Testing for Weak Password Change or Reset Functionalities"),
    Checklist("WSTG-ATHN-10", "Authentication Testing", "Testing for Weaker Authentication in Alternative Channel"),
    Checklist("WSTG-ATHZ-01", "Authorization Testing ", "Testing Directory Traversal File Include"),
    Checklist("WSTG-ATHZ-02", "Authorization Testing ", "Testing for Bypassing Authorization Schema"),
    Checklist("WSTG-ATHZ-03", "Authorization Testing ", "Testing for Privilege Escalation"),
    Checklist("WSTG-ATHZ-04", "Authorization Testing ", "Testing for Insecure Direct Object References"),
    Checklist("WSTG-SESS-01", "Session Management Testing", "Testing for Session Management Schema"),
    Checklist("WSTG-SESS-02", "Session Management Testing", "Testing for Cookies Attributes"),
    Checklist("WSTG-SESS-03", "Session Management Testing", "Testing for Session Fixation"),
    Checklist("WSTG-SESS-04", "Session Management Testing", "Testing for Exposed Session Variables"),
    Checklist("WSTG-SESS-05", "Session Management Testing", "Testing for Cross Site Request Forgery"),
    Checklist("WSTG-SESS-06", "Session Management Testing", "Testing for Logout Functionality"),
    Checklist("WSTG-SESS-07", "Session Management Testing", "Testing Session Timeout"),
    Checklist("WSTG-SESS-08", "Session Management Testing", "Testing for Session Puzzling"),
    Checklist("WSTG-SESS-09", "Session Management Testing", "Testing for Session Hijacking"),
    Checklist("WSTG-INPV-01", "Data Validation Testing", "Testing for Reflected Cross Site Scripting"),
    Checklist("WSTG-INPV-02", "Data Validation Testing", "Testing for Stored Cross Site Scripting"),
    Checklist("WSTG-INPV-03", "Data Validation Testing", "Testing for HTTP Verb Tampering"),
    Checklist("WSTG-INPV-04", "Data Validation Testing", "Testing for HTTP Parameter Pollution"),
    Checklist("WSTG-INPV-05", "Data Validation Testing", "Testing for SQL Injection"),
    Checklist("WSTG-INPV-06", "Data Validation Testing", "Testing for LDAP Injection"),
    Checklist("WSTG-INPV-07", "Data Validation Testing", "Testing for XML Injection"),
    Checklist("WSTG-INPV-08", "Data Validation Testing", "Testing for SSI Injection"),
    Checklist("WSTG-INPV-09", "Data Validation Testing", "Testing for XPath Injection"),
    Checklist("WSTG-INPV-10", "Data Validation Testing", "Testing for IMAP SMTP Injection"),
    Checklist("WSTG-INPV-11", "Data Validation Testing", "Testing for Code Injection"),
    Checklist("WSTG-INPV-12", "Data Validation Testing", "Testing for Command Injection"),
    Checklist("WSTG-INPV-13", "Data Validation Testing", "Testing for Format String Injection"),
    Checklist("WSTG-INPV-14", "Data Validation Testing", "Testing for Incubated Vulnerability"),
    Checklist("WSTG-INPV-15", "Data Validation Testing", "Testing for HTTP Splitting Smuggling"),
    Checklist("WSTG-INPV-16", "Data Validation Testing", "Testing for HTTP Incoming Requests"),
    Checklist("WSTG-INPV-17", "Data Validation Testing", "Testing for Host Header Injection"),
    Checklist("WSTG-INPV-18", "Data Validation Testing", "Testing for Server-side Template Injection"),
    Checklist("WSTG-INPV-19", "Data Validation Testing", "Testing for Server-Side Request Forgery"),
    Checklist("WSTG-ERRH-01", "Error Handling", "Testing for Improper Error Handling"),
    Checklist("WSTG-ERRH-02", "Error Handling", "Testing for Stack Traces"),
    Checklist("WSTG-CRYP-01", "Cryptography", "Testing for Weak Transport Layer Security"),
    Checklist("WSTG-CRYP-02", "Cryptography", "Testing for Padding Oracle"),
    Checklist("WSTG-CRYP-03", "Cryptography", "Testing for Sensitive Information Sent via Unencrypted Channels"),
    Checklist("WSTG-CRYP-04", "Cryptography", "Testing for Weak Encryption"),
    Checklist("WSTG-BUSL-01", "Business Logic Testing", "Test Business Logic Data Validation"),
    Checklist("WSTG-BUSL-02", "Business Logic Testing", "Test Ability to Forge Requests"),
    Checklist("WSTG-BUSL-03", "Business Logic Testing", "Test Integrity Checks"),
    Checklist("WSTG-BUSL-04", "Business Logic Testing", "Test for Process Timing"),
    Checklist("WSTG-BUSL-05", "Business Logic Testing", "Test Number of Times a Function Can be Used Limits"),
    Checklist("WSTG-BUSL-06", "Business Logic Testing", "Testing for the Circumvention of Work Flows"),
    Checklist("WSTG-BUSL-07", "Business Logic Testing", "Test Defenses Against Application Mis-use"),
    Checklist("WSTG-BUSL-08", "Business Logic Testing", "Test Upload of Unexpected File Types"),
    Checklist("WSTG-BUSL-09", "Business Logic Testing", "Test Upload of Malicious Files"),
    Checklist("WSTG-CLNT-01", "Client Side Testing", "Testing for DOM-Based Cross Site Scripting"),
    Checklist("WSTG-CLNT-02", "Client Side Testing", "Testing for JavaScript Execution"),
    Checklist("WSTG-CLNT-03", "Client Side Testing", "Testing for HTML Injection"),
    Checklist("WSTG-CLNT-04", "Client Side Testing", "Testing for Client Side URL Redirect"),
    Checklist("WSTG-CLNT-05", "Client Side Testing", "Testing for CSS Injection"),
    Checklist("WSTG-CLNT-06", "Client Side Testing", "Testing for Client Side Resource Manipulation"),
    Checklist("WSTG-CLNT-07", "Client Side Testing", "Test Cross Origin Resource Sharing"),
    Checklist("WSTG-CLNT-08", "Client Side Testing", "Testing for Cross Site Flashing"),
    Checklist("WSTG-CLNT-09", "Client Side Testing", "Testing for Clickjacking"),
    Checklist("WSTG-CLNT-10", "Client Side Testing", "Testing WebSockets"),
    Checklist("WSTG-CLNT-11", "Client Side Testing", "Test Web Messaging"),
    Checklist("WSTG-CLNT-12", "Client Side Testing", "Testing Browser Storage"),
    Checklist("WSTG-CLNT-13", "Client Side Testing", "Testing for Cross Site Script Inclusion"),
    Checklist("WSTG-APIT-01", "API Testing", "Testing GraphQL"),
)
